### ISSUE TITLE
Rainbow integration?

### ISSUE THREAD

**Issue by Vitruvia** [lu-ren/SerialExperimentsLain#1]
Hello. I love the theme, but I realize [rainbow-parenthesis](https://github.com/luochen1990/rainbow) plugin stopped working when I installed it. I removed the rainbow plugin and now all my parens display with the same light-blue color (at least in clojure, R and .vim files which is what I have tested).

 Is there any way to make this plugin work with that one or maybe integrate a functionality for colored parens? (From your screenshots it seems your parens display different colors when nested so maybe this functionality already exists but doesn't work for me?)

**Comment by lu-ren** [comment]
Honestly, I am not sure what the exact cause of the issue is. I created the theme through Vivify. What I am guessing is that there may be conflicts between your plugins.

**Comment by Vitruvia** [comment]
All good. I've deactivated rainbow and I'm doing fine without it so far. I did notice colorful parens in your screenshots, though. Are you using a different plugin for that?

**Comment by lu-ren** [comment]
I am also using rainbow parenthesis.

**Comment by Vitruvia** [comment]
Thanks! I just figured out the problem: for some reason my vim couldn't recognize the color names used for configuring rainbow parenthesis (firebrick, darkorange3...). I replaced them by the corresponding hex value and now everything is fixed.
